# Generated by Django 3.2.7 on 2022-02-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_tag_ordering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='note_title',
        ),
    ]
