# Generated by Django 3.2.7 on 2022-02-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_title_note_note_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_tag',
        ),
        migrations.AddField(
            model_name='note',
            name='note_tag',
            field=models.ManyToManyField(blank=True, default=0, to='base.Tag'),
        ),
    ]
