# Generated by Django 3.2.7 on 2022-02-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220204_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_tag',
            new_name='leaf_tag',
        ),
    ]
